In [481]:
import pandas as pd 
df=pd.read_csv('C:/Users/mamun/OneDrive/Desktop/Data_science_project/ML Zoomcamp/raw.githubusercontent.com_alexeygrigorev_mlbookcamp-code_master_chapter-02-car-price_data.csv')
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

### Data Preparation

In [482]:
 df.head().T

,0,1,2,3,4
Make,BMW,BMW,BMW,BMW,BMW
Model,1 Series M,1 Series,1 Series,1 Series,1 Series
Year,2011,2011,2011,2011,2011
Engine Fuel Type,premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required),premium unleaded (required)
Engine HP,335.0,300.0,300.0,230.0,230.0
Engine Cylinders,6.0,6.0,6.0,6.0,6.0
Transmission Type,MANUAL,MANUAL,MANUAL,MANUAL,MANUAL
Driven_Wheels,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive,rear wheel drive
Number of Doors,2.0,2.0,2.0,2.0,2.0
Market Category,"Factory Tuner,Luxury,High-Performance","Luxury,Performance","Luxury,High-Performance","Luxury,Performance",Luxury
Vehicle Size,Compact,Compact,Compact,Compact,Compact
Vehicle Style,Coupe,Convertible,Coupe,Coupe,Convertible
highway MPG,26,28,28,28,28
city mpg,19,19,20,18,18
Popularity,3916,3916,3916,3916,3916
MSRP,46135,40650,36350,29450,34500

In [483]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [484]:
df.columns.str.replace(' ', '_')

Index(['Make', 'Model', 'Year', 'Engine_Fuel_Type', 'Engine_HP',
       'Engine_Cylinders', 'Transmission_Type', 'Driven_Wheels',
       'Number_of_Doors', 'Market_Category', 'Vehicle_Size', 'Vehicle_Style',
       'highway_MPG', 'city_mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [485]:
df_filtered=df[['Make', 'Model', 'Year', 'Engine HP',
       'Engine Cylinders', 'Transmission Type',  'Vehicle Style',
       'highway MPG', 'city mpg', 'MSRP']]
df_filtered.head()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle Style,highway MPG,city mpg,MSRP
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,Coupe,26,19,46135
1,BMW,1 Series,2011,300.0,6.0,MANUAL,Convertible,28,19,40650
2,BMW,1 Series,2011,300.0,6.0,MANUAL,Coupe,28,20,36350
3,BMW,1 Series,2011,230.0,6.0,MANUAL,Coupe,28,18,29450
4,BMW,1 Series,2011,230.0,6.0,MANUAL,Convertible,28,18,34500

In [486]:
df_filtered.columns = df_filtered.columns.str.replace(' ', '_').str.lower()
df_filtered.head()

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,highway_mpg,city_mpg,msrp
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,Coupe,26,19,46135
1,BMW,1 Series,2011,300.0,6.0,MANUAL,Convertible,28,19,40650
2,BMW,1 Series,2011,300.0,6.0,MANUAL,Coupe,28,20,36350
3,BMW,1 Series,2011,230.0,6.0,MANUAL,Coupe,28,18,29450
4,BMW,1 Series,2011,230.0,6.0,MANUAL,Convertible,28,18,34500

In [487]:
df_filtered.isna().sum()

make                  0
model                 0
year                  0
engine_hp            69
engine_cylinders     30
transmission_type     0
vehicle_style         0
highway_mpg           0
city_mpg              0
msrp                  0
dtype: int64

In [488]:
df_filtered.fillna(0,inplace=True)

C:\Users\mamun\AppData\Local\Temp\ipykernel_6472\1862295627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered.fillna(0,inplace=True)

In [489]:
df_filtered.isna().sum()

make                 0
model                0
year                 0
engine_hp            0
engine_cylinders     0
transmission_type    0
vehicle_style        0
highway_mpg          0
city_mpg             0
msrp                 0
dtype: int64

In [490]:
df_filtered.rename(columns={"msrp": "price"}, inplace=True)

df_filtered.head()

C:\Users\mamun\AppData\Local\Temp\ipykernel_6472\3081227735.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered.rename(columns={"msrp": "price"}, inplace=True)

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,highway_mpg,city_mpg,price
0,BMW,1 Series M,2011,335.0,6.0,MANUAL,Coupe,26,19,46135
1,BMW,1 Series,2011,300.0,6.0,MANUAL,Convertible,28,19,40650
2,BMW,1 Series,2011,300.0,6.0,MANUAL,Coupe,28,20,36350
3,BMW,1 Series,2011,230.0,6.0,MANUAL,Coupe,28,18,29450
4,BMW,1 Series,2011,230.0,6.0,MANUAL,Convertible,28,18,34500

### Question 1
What is the most frequent observation (mode) for the column transmission_type?
* AUTOMATIC
* MANUAL
* AUTOMATED_MANUAL
* DIRECT_DRIVE

In [491]:
df_filtered['transmission_type'].value_counts()

transmission_type
AUTOMATIC           8266
MANUAL              2935
AUTOMATED_MANUAL     626
DIRECT_DRIVE          68
UNKNOWN               19
Name: count, dtype: int64

### Question 2
Create the correlation matrix for the numerical features of your dataset. In a correlation matrix, you compute the correlation coefficient between every pair of features in the dataset.

* What are the two features that have the biggest correlation in this dataset?

* engine_hp and year
* engine_hp and engine_cylinders
* highway_mpg and engine_cylinders
* highway_mpg and city_mpg

In [492]:
corr_matrix =  df_filtered[['engine_hp','year','engine_cylinders','highway_mpg','city_mpg']].corr()
corr_matrix

                  engine_hp      year  engine_cylinders  highway_mpg  city_mpg
engine_hp          1.000000  0.338714          0.774851    -0.415707 -0.424918
year               0.338714  1.000000         -0.040708     0.258240  0.198171
engine_cylinders   0.774851 -0.040708          1.000000    -0.614541 -0.587306
highway_mpg       -0.415707  0.258240         -0.614541     1.000000  0.886829
city_mpg          -0.424918  0.198171         -0.587306     0.886829  1.000000

### Make price binary
* Now we need to turn the price variable from numeric into a binary format.
* Let's create a variable above_average which is 1 if the price is above its mean value and 0 otherwise.

In [493]:
df_filtered['above_average'] = (df_filtered.price > df_filtered.price.mean()).astype('int')
df_filtered.head().T

C:\Users\mamun\AppData\Local\Temp\ipykernel_6472\3872267645.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['above_average'] = (df_filtered.price > df_filtered.price.mean()).astype('int')

                            0            1         2         3            4
make                      BMW          BMW       BMW       BMW          BMW
model              1 Series M     1 Series  1 Series  1 Series     1 Series
year                     2011         2011      2011      2011         2011
engine_hp               335.0        300.0     300.0     230.0        230.0
engine_cylinders          6.0          6.0       6.0       6.0          6.0
transmission_type      MANUAL       MANUAL    MANUAL    MANUAL       MANUAL
vehicle_style           Coupe  Convertible     Coupe     Coupe  Convertible
highway_mpg                26           28        28        28           28
city_mpg                   19           19        20        18           18
price                   46135        40650     36350     29450        34500
above_average               1            1         0         0            0

### Split the data
* Split your data in train/val/test sets with 60%/20%/20% distribution.
* Use Scikit-Learn for that (the train_test_split function) and set the seed to 42.
* Make sure that the target value (above_average) is not in your dataframe.

In [494]:
from sklearn.model_selection import train_test_split

df_train_full, df_test = train_test_split(df_filtered, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_train_full, test_size=0.25, random_state=42)

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train.above_average.values
y_val = df_val.above_average.values
y_test = df_test.above_average.values
# Print the shapes of the resulting sets to verify the distribution
print("Training set shape:", df_train.shape)
print("Validation set shape:", df_val.shape)
print("Test set shape:", df_test.shape)

Training set shape: (7148, 11)
Validation set shape: (2383, 11)
Test set shape: (2383, 11)

In [495]:
# removing above average from the train,test and validation sets
del df_train['above_average']
del df_val['above_average']
del df_test['above_average']

In [496]:
df_train_full = df_train_full.reset_index(drop=True)

df_train_full.above_average.value_counts(normalize=True)

above_average
0    0.723219
1    0.276781
Name: proportion, dtype: float64

In [497]:
df_train.head()

,make,model,year,engine_hp,engine_cylinders,transmission_type,vehicle_style,highway_mpg,city_mpg,price
0,Mitsubishi,Endeavor,2011,225.0,6.0,AUTOMATIC,4dr SUV,19,15,33599
1,Kia,Borrego,2009,276.0,6.0,AUTOMATIC,4dr SUV,21,17,26245
2,Lamborghini,Gallardo,2012,570.0,10.0,MANUAL,Convertible,20,12,248000
3,Chevrolet,Colorado,2016,200.0,4.0,AUTOMATIC,Crew Cab Pickup,27,20,24990
4,Pontiac,Vibe,2009,158.0,4.0,AUTOMATIC,4dr Hatchback,26,20,20475

### Question 3
* Calculate the mutual information score between above_average and other categorical variables in our dataset. 
* Use the training set only.
* Round the scores to 2 decimals using round(score, 2).
* Which of these variables has the lowest mutual information score?
make
model
transmission_type
vehicle_style

In [498]:
global_mean = df_train_full.above_average.mean()
round(global_mean, 3)

0.277

In [499]:
numerical = ['year', 'engine_hp', 'engine_cylinders', 'highway_mpg', 'city_mpg']
categorical = ['make', 'model','transmission_type', 'vehicle_style']

In [500]:
df_train_full[categorical].nunique()

make                  48
model                902
transmission_type      5
vehicle_style         16
dtype: int64

In [501]:
from sklearn.metrics import mutual_info_score

def mutual_info_price_score(series):
    return mutual_info_score(series, df_train_full.above_average)

In [502]:
categorical_columns = ["make", "model", "transmission_type", "vehicle_style"]

mi_scores = {}
for column in categorical_columns:
    mi_score = mutual_info_score(df_train[column], y_train)
    mi_scores[column] = round(mi_score, 2)

# Print the mutual information scores
for column, score in mi_scores.items():
    print(f"Mutual Information between {column} and above_average: {score:.2f}")
    
# Find the variable with the lowest mutual information score
lowest_mi_variable = min(mi_scores, key=mi_scores.get)
lowest_mi_score = mi_scores[lowest_mi_variable]

print(f'The variable with the lowest mutual information score is {lowest_mi_variable} with a score of {mi_scores[lowest_mi_variable]}')

Mutual Information between make and above_average: 0.24
Mutual Information between model and above_average: 0.46
Mutual Information between transmission_type and above_average: 0.02
Mutual Information between vehicle_style and above_average: 0.08
The variable with the lowest mutual information score is transmission_type with a score of 0.02

In [503]:
df_train_full[numerical].corrwith(df_train_full.above_average)

year                0.318753
engine_hp           0.660670
engine_cylinders    0.453162
highway_mpg        -0.134484
city_mpg           -0.157912
dtype: float64

### Question 4
* Now let's train a logistic regression.
* Remember that we have several categorical variables in the dataset. Include them using one-hot encoding.
* Fit the model on the training dataset.
* To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:
 model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)
* Calculate the accuracy on the validation dataset and round it to 2 decimal digits.
What accuracy did you get?

* 0.60
* 0.72
* 0.84
* 0.95

In [504]:
from sklearn.feature_extraction import DictVectorizer

In [505]:
# Combine training and validation datasets for one-hot encoding
X_combined = pd.concat([df_train[categorical], df_val[categorical]])
X_combined

              make           model transmission_type        vehicle_style
0       Mitsubishi        Endeavor         AUTOMATIC              4dr SUV
1              Kia         Borrego         AUTOMATIC              4dr SUV
2      Lamborghini        Gallardo            MANUAL          Convertible
3        Chevrolet        Colorado         AUTOMATIC      Crew Cab Pickup
4          Pontiac            Vibe         AUTOMATIC        4dr Hatchback
...            ...             ...               ...                  ...
2378          Ford  Explorer Sport         AUTOMATIC              2dr SUV
2379        Subaru         Outback         AUTOMATIC              4dr SUV
2380           GMC          Sonoma            MANUAL  Extended Cab Pickup
2381  Aston Martin      V8 Vantage  AUTOMATED_MANUAL                Coupe
2382      Cadillac             CTS         AUTOMATIC                Sedan

[9531 rows x 4 columns]

In [506]:
dv = DictVectorizer(sparse=False)

train_dicts = df_train[categorical+numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dicts)

val_dicts = df_val[categorical+numerical].to_dict(orient='records')
X_val = dv.transform(val_dicts)

In [507]:
dv.feature_names_

['city_mpg',
 'engine_cylinders',
 'engine_hp',
 'highway_mpg',
 'make=Acura',
 'make=Alfa Romeo',
 'make=Aston Martin',
 'make=Audi',
 'make=BMW',
 'make=Bentley',
 'make=Bugatti',
 'make=Buick',
 'make=Cadillac',
 'make=Chevrolet',
 'make=Chrysler',
 'make=Dodge',
 'make=FIAT',
 'make=Ferrari',
 'make=Ford',
 'make=GMC',
 'make=Genesis',
 'make=HUMMER',
 'make=Honda',
 'make=Hyundai',
 'make=Infiniti',
 'make=Kia',
 'make=Lamborghini',
 'make=Land Rover',
 'make=Lexus',
 'make=Lincoln',
 'make=Lotus',
 'make=Maserati',
 'make=Maybach',
 'make=Mazda',
 'make=McLaren',
 'make=Mercedes-Benz',
 'make=Mitsubishi',
 'make=Nissan',
 'make=Oldsmobile',
 'make=Plymouth',
 'make=Pontiac',
 'make=Porsche',
 'make=Rolls-Royce',
 'make=Saab',
 'make=Scion',
 'make=Spyker',
 'make=Subaru',
 'make=Suzuki',
 'make=Tesla',
 'make=Toyota',
 'make=Volkswagen',
 'make=Volvo',
 'model=1 Series',
 'model=100',
 'model=124 Spider',
 'model=190-Class',
 'model=2',
 'model=2 Series',
 'model=200',
 'model=200SX',
 'model=240',
 'model=240SX',
 'model=3',
 'model=3 Series',
 'model=3 Series Gran Turismo',
 'model=300',
 'model=300-Class',
 'model=3000GT',
 'model=300M',
 'model=300ZX',
 'model=323',
 'model=350-Class',
 'model=350Z',
 'model=360',
 'model=370Z',
 'model=4 Series',
 'model=4 Series Gran Coupe',
 'model=400-Class',
 'model=420-Class',
 'model=456M',
 'model=458 Italia',
 'model=4C',
 'model=4Runner',
 'model=5',
 'model=5 Series',
 'model=5 Series Gran Turismo',
 'model=500',
 'model=500-Class',
 'model=500L',
 'model=500X',
 'model=500e',
 'model=550',
 'model=560-Class',
 'model=57',
 'model=570S',
 'model=575M',
 'model=599',
 'model=6',
 'model=6 Series',
 'model=6 Series Gran Coupe',
 'model=600-Class',
 'model=6000',
 'model=612 Scaglietti',
 'model=62',
 'model=626',
 'model=7 Series',
 'model=740',
 'model=760',
 'model=780',
 'model=8 Series',
 'model=80',
 'model=850',
 'model=9-2X',
 'model=9-3',
 'model=9-3 Griffin',
 'model=9-4X',
 'model=9-5',
 'model=9-7X',
 'model=90',
 'model=900',
 'model=9000',
 'model=911',
 'model=928',
 'model=929',
 'model=940',
 'model=944',
 'model=960',
 'model=968',
 'model=A3',
 'model=A4',
 'model=A5',
 'model=A6',
 'model=A7',
 'model=A8',
 'model=ALPINA B6 Gran Coupe',
 'model=ALPINA B7',
 'model=AMG GT',
 'model=ATS',
 'model=ATS Coupe',
 'model=Acadia',
 'model=Acadia Limited',
 'model=Accent',
 'model=Acclaim',
 'model=Accord',
 'model=Accord Crosstour',
 'model=Accord Hybrid',
 'model=Accord Plug-In Hybrid',
 'model=Achieva',
 'model=ActiveHybrid 5',
 'model=ActiveHybrid 7',
 'model=ActiveHybrid X6',
 'model=Aerio',
 'model=Aerostar',
 'model=Alero',
 'model=Allante',
 'model=Altima',
 'model=Altima Hybrid',
 'model=Amanti',
 'model=Armada',
 'model=Arnage',
 'model=Aspen',
 'model=Aspire',
 'model=Astro',
 'model=Astro Cargo',
 'model=Aurora',
 'model=Avalanche',
 'model=Avalon',
 'model=Avalon Hybrid',
 'model=Avenger',
 'model=Aventador',
 'model=Aveo',
 'model=Aviator',
 'model=Axxess',
 'model=Azera',
 'model=Aztek',
 'model=Azure',
 'model=Azure T',
 'model=B-Class Electric Drive',
 'model=B-Series',
 'model=B-Series Pickup',
 'model=B-Series Truck',
 'model=B9 Tribeca',
 'model=BRZ',
 'model=Baja',
 'model=Beetle',
 'model=Beetle Convertible',
 'model=Beretta',
 'model=Black Diamond Avalanche',
 'model=Blackwood',
 'model=Blazer',
 'model=Bonneville',
 'model=Borrego',
 'model=Boxster',
 'model=Bravada',
 'model=Breeze',
 'model=Bronco',
 'model=Bronco II',
 'model=Brooklands',
 'model=Brougham',
 'model=C-Class',
 'model=C-Max Hybrid',
 'model=C/K 1500 Series',
 'model=C/K 2500 Series',
 'model=C30',
 'model=C43 AMG',
 'model=C70',
 'model=C8',
 'model=CC',
 'model=CL',
 'model=CL-Class',
 'model=CLA-Class',
 'model=CLK-Class',
 'model=CLS-Class',
 'model=CR-V',
 'model=CR-Z',
 'model=CT6',
 'model=CTS',
 'model=CTS Coupe',
 'model=CTS Wagon',
 'model=CTS-V',
 'model=CTS-V Coupe',
 'model=CTS-V Wagon',
 'model=CX-3',
 'model=CX-5',
 'model=CX-7',
 'model=CX-9',
 'model=Cabrio',
 'model=Cabriolet',
 'model=Cadenza',
 'model=Caliber',
 'model=Camaro',
 'model=Camry',
 'model=Camry Hybrid',
 'model=Camry Solara',
 'model=Canyon',
 'model=Caprice',
 'model=Captiva Sport',
 'model=Caravan',
 'model=Carrera GT',
 'model=Cascada',
 'model=Catera',
 'model=Cavalier',
 'model=Cayenne',
 'model=Cayman',
 'model=Cayman S',
 'model=Celebrity',
 'model=Celica',
 'model=Century',
 'model=Challenger',
 'model=Charger',
 'model=Chevy Van',
 'model=City Express',
 'model=Civic',
 'model=Civic CRX',
 'model=Civic del Sol',
 'model=Classic',
 'model=Cobalt',
 'model=Colorado',
 'model=Colt',
 'model=Concorde',
 'model=Continental',
 'model=Continental Flying Spur',
 'model=Continental Flying Spur Speed',
 'model=Continental GT',
 'model=Continental GT Speed',
 'model=Continental GT Speed Convertible',
 'model=Continental GTC',
 'model=Continental GTC Speed',
 'model=Continental Supersports',
 'model=Continental Supersports Convertible',
 'model=Contour',
 'model=Corniche',
 'model=Corolla',
 'model=Corolla iM',
 'model=Corrado',
 'model=Corvette',
 'model=Corvette Stingray',
 'model=Coupe',
 'model=Cressida',
 'model=Crossfire',
 'model=Crosstour',
 'model=Crosstrek',
 'model=Crown Victoria',
 'model=Cruze',
 'model=Cruze Limited',
 'model=Cube',
 'model=Custom Cruiser',
 'model=Cutlass',
 'model=Cutlass Calais',
 'model=Cutlass Ciera',
 'model=Cutlass Supreme',
 'model=DB9',
 'model=DB9 GT',
 'model=DBS',
 'model=DTS',
 'model=Dakota',
 'model=Dart',
 'model=Dawn',
 'model=Daytona',
 'model=DeVille',
 'model=Defender',
 'model=Diablo',
 'model=Diamante',
 'model=Discovery',
 'model=Discovery Series II',
 'model=Discovery Sport',
 'model=Durango',
 'model=Dynasty',
 'model=E-150',
 'model=E-250',
 'model=E-Class',
 'model=E-Series Van',
 'model=E-Series Wagon',
 'model=E55 AMG',
 'model=ECHO',
 'model=ES 250',
 'model=ES 300',
 'model=ES 300h',
 'model=EX',
 'model=EX35',
 'model=Eclipse',
 'model=Eclipse Spyder',
 'model=Edge',
 'model=Eighty-Eight',
 'model=Eighty-Eight Royale',
 'model=Elantra',
 'model=Elantra Coupe',
 'model=Elantra GT',
 'model=Elantra Touring',
 'model=Eldorado',
 'model=Electra',
 'model=Element',
 'model=Elise',
 'model=Enclave',
 'model=Encore',
 'model=Endeavor',
 'model=Entourage',
 'model=Envision',
 'model=Envoy',
 'model=Envoy XL',
 'model=Envoy XUV',
 'model=Eos',
 'model=Equator',
 'model=Equinox',
 'model=Equus',
 'model=Escalade',
 'model=Escalade ESV',
 'model=Escalade EXT',
 'model=Escalade Hybrid',
 'model=Escape',
 'model=Escape Hybrid',
 'model=Escort',
 'model=Esprit',
 'model=Esteem',
 'model=EuroVan',
 'model=Evora',
 'model=Excel',
 'model=Exige',
 'model=Expedition',
 'model=Explorer',
 'model=Explorer Sport',
 'model=Explorer Sport Trac',
 'model=Expo',
 'model=Express',
 'model=Express Cargo',
 'model=F-150',
 'model=F-150 Heritage',
 'model=F-150 SVT Lightning',
 'model=F-250',
 'model=F12 Berlinetta',
 'model=F430',
 'model=FF',
 'model=FJ Cruiser',
 'model=FR-S',
 'model=FX',
 'model=FX35',
 'model=FX45',
 'model=FX50',
 'model=Festiva',
 'model=Fiesta',
 'model=Firebird',
 'model=Fit',
 'model=Five Hundred',
 'model=Fleetwood',
 'model=Flex',
 'model=Flying Spur',
 'model=Focus',
 'model=Focus ST',
 'model=Forenza',
 'model=Forester',
 'model=Forte',
 'model=Fox',
 'model=Freelander',
 'model=Freestar',
 'model=Freestyle',
 'model=Frontier',
 'model=Fusion',
 'model=Fusion Hybrid',
 'model=G Convertible',
 'model=G Coupe',
 'model=G Sedan',
 'model=G-Class',
 'model=G20',
 'model=G3',
 'model=G35',
 'model=G37',
 'model=G37 Convertible',
 'model=G37 Coupe',
 'model=G37 Sedan',
 'model=G5',
 'model=G6',
 'model=G8',
 'model=G80',
 'model=GL-Class',
 'model=GLA-Class',
 'model=GLC-Class',
 'model=GLE-Class',
 'model=GLE-Class Coupe',
 'model=GLI',
 'model=GLK-Class',
 'model=GLS-Class',
 'model=GS 200t',
 'model=GS 300',
 'model=GS 350',
 'model=GS 400',
 'model=GS 430',
 'model=GS 450h',
 'model=GS 460',
 'model=GT',
 'model=GT-R',
 'model=GTI',
 'model=GTO',
 'model=GX 460',
 'model=GX 470',
 'model=Galant',
 'model=Gallardo',
 'model=Genesis',
 'model=Genesis Coupe',
 'model=Ghibli',
 'model=Ghost',
 'model=Ghost Series II',
 'model=Golf',
 'model=Golf Alltrack',
 'model=Golf GTI',
 'model=Golf R',
 'model=Golf SportWagen',
 'model=GranSport',
 'model=GranTurismo',
 'model=GranTurismo Convertible',
 'model=Grand Am',
 'model=Grand Caravan',
 'model=Grand Prix',
 'model=Grand Vitara',
 'model=Grand Voyager',
 'model=H3',
 'model=H3T',
 'model=HHR',
 'model=HR-V',
 'model=HS 250h',
 'model=Highlander',
 'model=Highlander Hybrid',
 'model=Horizon',
 'model=Huracan',
 'model=I30',
 'model=I35',
 'model=ILX',
 'model=ILX Hybrid',
 'model=IS 200t',
 'model=IS 250',
 'model=IS 250 C',
 'model=IS 300',
 'model=IS 350',
 'model=IS 350 C',
 'model=IS F',
 'model=Impala',
 'model=Impala Limited',
 'model=Imperial',
 'model=Impreza',
 'model=Impreza WRX',
 'model=Insight',
 'model=Integra',
 'model=Intrepid',
 'model=Intrigue',
 'model=J30',
 'model=JX',
 'model=Jetta',
 'model=Jetta GLI',
 'model=Jetta Hybrid',
 'model=Jetta SportWagen',
 'model=Jimmy',
 'model=Journey',
 'model=Juke',
 'model=Justy',
 'model=K900',
 'model=Kizashi',
 'model=LFA',
 'model=LHS',
 'model=LR2',
 'model=LR3',
 'model=LR4',
 'model=LS',
 'model=LS 400',
 'model=LS 430',
 'model=LS 460',
 'model=LS 600h L',
 'model=LSS',
 'model=LTD Crown Victoria',
 'model=LX 450',
 'model=LX 470',
 'model=LX 570',
 'model=LaCrosse',
 'model=Lancer',
 'model=Lancer Evolution',
 'model=Lancer Sportback',
 'model=Land Cruiser',
 'model=Laser',
 'model=Le Baron',
 'model=Le Mans',
 'model=LeSabre',
 'model=Leaf',
 'model=Legacy',
 'model=Legend',
 'model=Levante',
 'model=Loyale',
 'model=Lucerne',
 'model=Lumina',
 'model=Lumina Minivan',
 'model=M',
 'model=M-Class',
 'model=M2',
 'model=M3',
 'model=M30',
 'model=M35',
 'model=M37',
 'model=M4',
 'model=M45',
 'model=M5',
 'model=M56',
 'model=M6',
 'model=M6 Gran Coupe',
 'model=MDX',
 'model=MKC',
 'model=MKS',
 'model=MKT',
 'model=MKX',
 'model=MKZ',
 'model=MKZ Hybrid',
 'model=MP4-12C',
 'model=MPV',
 'model=MR2',
 'model=MR2 Spyder',
 'model=MX-3',
 'model=MX-5 Miata',
 'model=MX-6',
 'model=Macan',
 'model=Magnum',
 'model=Malibu',
 'model=Malibu Classic',
 'model=Malibu Hybrid',
 'model=Malibu Limited',
 'model=Malibu Maxx',
 'model=Mark LT',
 'model=Mark VII',
 'model=Mark VIII',
 'model=Matrix',
 'model=Maxima',
 'model=Maybach',
 'model=Mazdaspeed 3',
 'model=Mazdaspeed MX-5 Miata',
 'model=Mazdaspeed Protege',
 'model=Metris',
 'model=Metro',
 'model=Mighty Max Pickup',
 'model=Millenia',
 'model=Mirage',
 'model=Mirage G4',
 'model=Model S',
 'model=Monaco',
 'model=Montana',
 'model=Montana SV6',
 'model=Monte Carlo',
 'model=Montero',
 'model=Montero Sport',
 'model=Mulsanne',
 'model=Murano',
 'model=Murano CrossCabriolet',
 'model=Murcielago',
 'model=Mustang',
 'model=Mustang SVT Cobra',
 'model=NSX',
 'model=NV200',
 'model=NX',
 'model=NX 200t',
 'model=NX 300h',
 'model=Navajo',
 'model=Navigator',
 'model=Neon',
 'model=New Beetle',
 'model=New Yorker',
 'model=Ninety-Eight',
 'model=Nitro',
 'model=Odyssey',
 'model=Omni',
 'model=Optima',
 'model=Optima Hybrid',
 'model=Outback',
 'model=Outlander',
 'model=Outlander Sport',
 'model=PT Cruiser',
 'model=Pacifica',
 'model=Panamera',
 'model=Park Avenue',
 'model=Paseo',
 'model=Passat',
 'model=Passport',
 'model=Pathfinder',
 'model=Phaeton',
 'model=Phantom',
 'model=Phantom Coupe',
 'model=Phantom Drophead Coupe',
 'model=Pickup',
 'model=Pilot',
 'model=Precis',
 'model=Prelude',
 'model=Previa',
 'model=Prius',
 'model=Prius Prime',
 'model=Prius c',
 'model=Prius v',
 'model=Prizm',
 'model=Probe',
 'model=Protege',
 'model=Protege5',
 'model=Prowler',
 'model=Q3',
 'model=Q40',
 'model=Q45',
 'model=Q5',
 'model=Q50',
 'model=Q60 Convertible',
 'model=Q60 Coupe',
 'model=Q7',
 'model=Q70',
 'model=QX',
 'model=QX4',
 'model=QX50',
 'model=QX56',
 'model=QX60',
 'model=QX70',
 'model=QX80',
 'model=Quattroporte',
 'model=Quest',
 'model=R-Class',
 'model=R32',
 'model=R8',
 'model=RAM 150',
 'model=RAM 250',
 'model=RAV4',
 'model=RAV4 EV',
 'model=RAV4 Hybrid',
 'model=RC 200t',
 'model=RC 300',
 'model=RC 350',
 'model=RDX',
 'model=RL',
 'model=RLX',
 'model=RS 4',
 'model=RS 5',
 'model=RS 7',
 'model=RSX',
 'model=RX 300',
 'model=RX 330',
 'model=RX 350',
 'model=RX 400h',
 'model=RX 450h',
 'model=RX-7',
 'model=RX-8',
 'model=Rabbit',
 'model=Raider',
 'model=Rainier',
 'model=Rally Wagon',
 'model=Ram 50 Pickup',
 'model=Ram Cargo',
 'model=Ram Pickup 1500',
 'model=Ram Van',
 'model=Ram Wagon',
 'model=Ramcharger',
 'model=Range Rover',
 'model=Range Rover Evoque',
 'model=Range Rover Sport',
 'model=Ranger',
 'model=Rapide',
 'model=Rapide S',
 'model=Reatta',
 'model=Regal',
 'model=Regency',
 'model=Rendezvous',
 'model=Reno',
 'model=Reventon',
 'model=Ridgeline',
 'model=Rio',
 'model=Riviera',
 'model=Roadmaster',
 'model=Rogue',
 'model=Rogue Select',
 'model=Rondo',
 'model=Routan',
 'model=S-10',
 'model=S-10 Blazer',
 'model=S-15',
 'model=S-15 Jimmy',
 'model=S-Class',
 'model=S2000',
 'model=S3',
 'model=S4',
 'model=S40',
 'model=S5',
 'model=S6',
 'model=S60',
 'model=S60 Cross Country',
 'model=S7',
 'model=S70',
 'model=S8',
 'model=S80',
 'model=S90',
 'model=SC 300',
 'model=SC 400',
 'model=SC 430',
 'model=SL-Class',
 'model=SLC-Class',
 'model=SLK-Class',
 'model=SLR McLaren',
 'model=SLS AMG',
 'model=SLS AMG GT',
 'model=SLS AMG GT Final Edition',
 'model=SLX',
 'model=SQ5',
 'model=SRT Viper',
 'model=SRX',
 'model=STS',
 'model=STS-V',
 'model=SVX',
 'model=SX4',
 'model=Safari',
 'model=Safari Cargo',
 'model=Samurai',
 'model=Santa Fe',
 'model=Santa Fe Sport',
 'model=Savana',
 'model=Savana Cargo',
 'model=Scoupe',
 'model=Sebring',
 'model=Sedona',
 'model=Sentra',
 'model=Sephia',
 'model=Sequoia',
 'model=Seville',
 'model=Shadow',
 'model=Shelby GT350',
 'model=Shelby GT500',
 'model=Sidekick',
 'model=Sienna',
 'model=Sierra 1500',
 'model=Sierra 1500 Classic',
 'model=Sierra 1500 Hybrid',
 'model=Sierra 1500HD',
 'model=Sierra C3',
 'model=Sierra Classic 1500',
 'model=Sigma',
 'model=Silhouette',
 'model=Silver Seraph',
 'model=Silverado 1500',
 'model=Silverado 1500 Classic',
 'model=Silverado 1500 Hybrid',
 'model=Skylark',
 'model=Solstice',
 'model=Sonata',
 'model=Sonata Hybrid',
 'model=Sonic',
 'model=Sonoma',
 'model=Sorento',
 'model=Soul',
 'model=Soul EV',
 'model=Spark',
 'model=Spark EV',
 'model=Spectra',
 'model=Spirit',
 'model=Sportage',
 'model=Sportvan',
 'model=Spyder',
 'model=Stanza',
 'model=Stealth',
 'model=Stratus',
 'model=Suburban',
 'model=Sunbird',
 'model=Sundance',
 'model=Sunfire',
 'model=Supra',
 'model=Swift',
 'model=Syclone',
 'model=T100',
 'model=TL',
 'model=TLX',
 'model=TSX',
 'model=TSX Sport Wagon',
 'model=TT',
 'model=TTS',
 'model=Tacoma',
 'model=Tahoe',
 'model=Tahoe Hybrid',
 'model=Tahoe Limited/Z71',
 'model=Taurus',
 'model=Taurus X',
 'model=Tempo',
 'model=Tercel',
 'model=Terrain',
 'model=Terraza',
 'model=Thunderbird',
 'model=Tiburon',
 'model=Tiguan',
 'model=Titan',
 'model=Toronado',
 'model=Torrent',
 'model=Touareg',
 'model=Touareg 2',
 'model=Town Car',
 'model=Town and Country',
 'model=Tracker',
 'model=TrailBlazer',
 'model=TrailBlazer EXT',
 'model=Trans Sport',
 'model=Transit Connect',
 'model=Transit Wagon',
 'model=Traverse',
 'model=Trax',
 'model=Tribeca',
 'model=Tribute',
 'model=Tribute Hybrid',
 'model=Truck',
 'model=Tucson',
 'model=Tundra',
 'model=Typhoon',
 'model=Uplander',
 'model=V12 Vanquish',
 'model=V12 Vantage',
 'model=V12 Vantage S',
 'model=V40',
 'model=V50',
 'model=V60',
 'model=V60 Cross Country',
 'model=V70',
 'model=V8 Vantage',
 'model=Van',
 'model=Vanagon',
 'model=Vandura',
 'model=Vanquish',
 'model=Vanwagon',
 'model=Veloster',
 'model=Venture',
 'model=Venza',
 'model=Veracruz',
 'model=Verano',
 'model=Verona',
 'model=Versa',
 'model=Versa Note',
 'model=Veyron 16.4',
 'model=Vibe',
 'model=Vigor',
 'model=Viper',
 'model=Virage',
 'model=Vitara',
 'model=Voyager',
 'model=WRX',
 'model=Windstar',
 'model=Windstar Cargo',
 'model=Wraith',
 'model=X-90',
 'model=X1',
 'model=X3',
 'model=X4',
 'model=X5',
 'model=X5 M',
 'model=X6',
 'model=X6 M',
 'model=XC',
 'model=XC60',
 'model=XC70',
 'model=XC90',
 'model=XG300',
 'model=XG350',
 'model=XL-7',
 'model=XL7',
 'model=XLR',
 'model=XLR-V',
 'model=XT',
 'model=XT5',
 'model=XTS',
 'model=XV Crosstrek',
 'model=Xterra',
 'model=Yaris',
 'model=Yaris iA',
 'model=Yukon',
 'model=Yukon Denali',
 'model=Yukon Hybrid',
 'model=Yukon XL',
 'model=Z3',
 'model=Z4',
 'model=Z4 M',
 'model=Z8',
 'model=ZDX',
 'model=allroad',
 'model=allroad quattro',
 'model=e-Golf',
 'model=i-MiEV',
 'model=i3',
 'model=iA',
 'model=iQ',
 'model=tC',
 'model=xA',
 'model=xB',
 'model=xD',
 'transmission_type=AUTOMATED_MANUAL',
 'transmission_type=AUTOMATIC',
 'transmission_type=DIRECT_DRIVE',
 'transmission_type=MANUAL',
 'transmission_type=UNKNOWN',
 'vehicle_style=2dr Hatchback',
 'vehicle_style=2dr SUV',
 'vehicle_style=4dr Hatchback',
 'vehicle_style=4dr SUV',
 'vehicle_style=Cargo Minivan',
 'vehicle_style=Cargo Van',
 'vehicle_style=Convertible',
 'vehicle_style=Convertible SUV',
 'vehicle_style=Coupe',
 'vehicle_style=Crew Cab Pickup',
 'vehicle_style=Extended Cab Pickup',
 'vehicle_style=Passenger Minivan',
 'vehicle_style=Passenger Van',
 'vehicle_style=Regular Cab Pickup',
 'vehicle_style=Sedan',
 'vehicle_style=Wagon',
 'year']

In [508]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)

model.fit(X_train, y_train)
accuracy_with_all_features = accuracy_score(y_val, model.predict(X_val))
print(accuracy_with_all_features)

0.946286193873269

### Question - 5

Let's find the least useful feature using the feature elimination technique.

 Train a model with all these features (using the same parameters as in Q4).

2. Now exclude each feature from this set and train a model without it. Record the accuracy for each model.

3. For each feature, calculate the difference between the original accuracy and the accuracy without the feature.

4. Determine which feature has the smallest difference.


* year
* engine_hp
* transmission_type
* city_mpg
Note: the difference doesn't have to be positive

In [509]:
X_train.shape

(7148, 943)

In [510]:
all_features = df_train[categorical+numerical]
val_all_features = df_val[categorical+numerical]
least_useful_feature = None
smallest_difference = float('inf')

for feature in all_features.columns:
    X_train_subset = all_features.drop(feature, axis=1)
    X_val_subset = val_all_features.drop(feature, axis=1)
    
    train_dicts = X_train_subset.to_dict(orient='records')
    X_train = dv.fit_transform(train_dicts)

    val_dicts = X_val_subset.to_dict(orient='records')
    X_val = dv.transform(val_dicts)
    
    model.fit(X_train, y_train)
    accuracy_without_feature = accuracy_score(y_val, model.predict(X_val))

    difference = abs(accuracy_with_all_features - accuracy_without_feature)
    print(feature, difference)
    if difference < smallest_difference:
        smallest_difference = difference
        least_useful_feature = feature

least_useful_feature

make 0.002937473772555599
model 0.022240872849349502
transmission_type 0.0012589173310951773
vehicle_style 0.003776751993285754
year 0.0016785564414604215
engine_hp 0.015946286193873282
engine_cylinders 0.0008392782207301552
highway_mpg 0.0020981955518254436
city_mpg 0.0004196391103650221

'city_mpg'

### Question 6
* For this question, we'll see how to use a linear regression model from Scikit-Learn.
* We'll need to use the original column price. Apply the logarithmic transformation to this column.
* Fit the Ridge regression model on the training data with a solver 'sag'. Set the seed to 42.
* This model also has a parameter alpha. Let's try the following values: [0, 0.01, 0.1, 1, 10].
* Round your RMSE scores to 3 decimal digits.

Which of these alphas leads to the best RMSE on the validation set?

* 0
* 0.01
* 0.1
* 1
* 10

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
y_train_p = np.log1p(df_train.price.values)
y_val_p = np.log1p(df_val.price.values)
y_test_p = np.log1p(df_test.price.values)
alpha_values = [0, 0.01, 0.1, 1, 10]
# Initialize a dictionary to store RMSE scores for different alphas
rmse_scores = {}

# Iterate through each alpha value
for alpha in alpha_values:
    rmse_scores = 0
    model_r = Ridge(alpha=alpha,solver='sag', random_state=42)
    model_r.fit(X_train, y_train_p)
    y_pred = model_r.predict(X_val)
    rmse_val = mean_squared_error(y_val_p, y_pred, squared=False)
    print(alpha, round(rmse_scores,3))
    
# Print RMSE scores for different alpha values
for alpha, rmse in rmse_scores.items():
    print(f"Alpha = {alpha}: RMSE = {rmse:.3f}")

C:\Users\mamun\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

0 0

C:\Users\mamun\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

0.01 0

C:\Users\mamun\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

0.1 0

C:\Users\mamun\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

1 0

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
y_train_p = np.log1p(df_train.price.values)
y_val_p = np.log1p(df_val.price.values)
y_test_p = np.log1p(df_test.price.values)
alpha_values = [0, 0.01, 0.1, 1, 10]
rmse_scores = {}
for alpha in alpha_values:
    rmse_val = 0
    model_r = Ridge(alpha=alpha,solver='sag', random_state=42)
    model_r.fit(X_train, y_train_p)
    y_pred = model_r.predict(X_val)
    rmse_val = mean_squared_error(y_val_p, y_pred, squared=False)
    print(alpha, round(rmse_val,3))